import swaggerAutogen from 'swagger-autogen';
import dotenv from 'dotenv';
const outputFile = '../swagger/swagger_output.json';
const endpointsFiles = ['./src/index.ts'];
const PORT = process.env.PORT as string
const doc = {
  info: {
    title: 'Express API with Swagger',
    version: '1.0.0',
    description: 'Documentation automatically generated by swagger-autogen.',
    contact: {
        name: 'Developer',
        email: 'satishghode9075@gmail.com'
    }
  },
  host: `localhost:8083`,
  schemes: ['http'],
};

swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  require('../index'); // Your project's root file
});

